import"./app.min.js";const X=()=>{const A=document.querySelectorAll("[data-fls-marquee]"),E={inner:"data-fls-marquee-inner",item:"data-fls-marquee-item"};if(!A.length)return;const{head:b}=document,F=(t,a)=>{let e;return(...o)=>{e&&clearTimeout(e),e=setTimeout(()=>{a(...o),e=null},t)}},M=t=>{if(!t&&!isFunction(t))return;let a=0;const e=()=>{const o=window.innerWidth;a!==o&&(a=o,t())};window.addEventListener("resize",F(50,e)),e()},H=t=>{if(!t)return;const a=t,e=a.children;if(!e.length)return;Array.from(e).forEach(d=>d.setAttribute(E.item,""));const o=`<div ${E.inner}>${a.innerHTML}</div>`;a.innerHTML=o},h=(t,a)=>a?t.offsetHeight:t.offsetWidth;A.forEach(t=>{var a;if(!t)return;H(t);const e=t.firstElementChild;let o=[];if(!e)return;const d=parseFloat(t.getAttribute("data-fls-marquee-space")),x=t.querySelectorAll(`[${E.item}]`),N=parseFloat(t.getAttribute("data-fls-marquee-speed"))/10||100,P=t.hasAttribute("data-fls-marquee-pause-mouse-enter"),f=t.getAttribute("data-fls-marquee-direction"),i=f==="bottom"||f==="top",g=`marqueeAnimation-${Math.floor(Math.random()*1e7)}`;let y=parseFloat((a=window.getComputedStyle(x[0]))==null?void 0:a.getPropertyValue("margin-right")),m=y||(isNaN(d)?30:d),p=parseFloat(t.getAttribute("data-fls-marquee-start"))||0,v=0,l=0,q=0,C=e.children.length,c=0,w=0;const R=()=>{p&&e.addEventListener("animationiteration",S),P&&(e.removeEventListener("mouseenter",$),e.removeEventListener("mouseleave",$),e.addEventListener("mouseenter",$),e.addEventListener("mouseleave",$))},S=()=>{p=0,e.removeEventListener("animationiteration",S),T()},k=n=>{let r="display: flex; flex-wrap: nowrap;";i?(r+=`
				flex-direction: column;
				position: relative;
				will-change: transform;`,f==="bottom"&&(r+=`top: -${n}px;`)):(r+=`
				position: relative;
				will-change: transform;`,f==="right"&&(r+=`inset-inline-start: -${n}px;;`)),e.style.cssText=r},V=n=>{switch(f){case"right":case"bottom":return n;default:return-n}},W=()=>{const n=`@keyframes ${g} {
					 0% {
						 transform: translate${i?"Y":"X"}(${!i&&window.stateRtl?-p:p}%);
					 }
					 100% {
						 transform: translate${i?"Y":"X"}(${V(!i&&window.stateRtl?-l:l)}px);
					 }
				 }`,r=document.createElement("style");r.classList.add(g),r.innerHTML=n,b.append(r),e.style.animation=`${g} ${(l+p*l/100)/N}s infinite linear`},z=()=>{v=l=q=w=c=0;const n=h(t,i);let r=Array.from(e.children);if(!r.length)return;o.length?r=[...o]:o=r.map(s=>s),e.style.display="flex",i&&(e.style.flexDirection="column"),e.innerHTML="",r.forEach(s=>{e.append(s)}),r.forEach(s=>{i?s.style.marginBottom=`${m}px`:(s.style.marginRight=`${m}px`,s.style.flexShrink=0);const u=h(s,i);return v+=u+m,l+=u+m,q+=u+m,w+=1,u});const L=n*2+q;for(;v<L;c+=1){r[c]||(c=0);const s=r[c].cloneNode(!0),u=e.children[c];e.append(s),v+=h(u,i)+m,(l<n||w%C!==0)&&(w+=1,l+=h(u,i)+m)}k(l)},B=()=>{y&&(x.forEach(n=>n.style.removeProperty("margin-right")),y=parseFloat(window.getComputedStyle(x[0]).getPropertyValue("margin-right")),m=y||(isNaN(d)?30:d))},D=()=>{B(),z(),W(),R()},T=()=>{var n;(n=b.querySelector(`.${g}`))==null||n.remove(),D()},$=n=>{const{type:r,target:L}=n;L.style.animationPlayState=r==="mouseenter"?"paused":"running"};M(T)})};X();
